### ISSUE TITLE
Does not remove .git from url when non https domain. 

### ISSUE THREAD

**Issue by overlandandseas** [mark-adams/open-on-bitbucket#3]
For Stash/Bitbucket-Server, the `bitbucketCloudRepoUrl` function does not remove the .git from the url when the url is a non https.

**Comment by mark-adams** [comment]
Thanks @Overlandandseas! Any chance you could right a quick test for this?

**Comment by overlandandseas** [comment]
@mark-adams Sure thing, test has been added to the existing PR. Without the change test will fail. 
Sorry for all the failing builds, pretty new to TravisCI.
